# Ultra-comprehensive final cleanup of ALL Spanish text
$file = "app\components\NumberPage.tsx"
$content = Get-Content -Path $file -Raw -Encoding UTF8

Write-Host "Final cleanup: translating ALL remaining Spanish..."

# Fix encoding
$content = $content -replace 'FÃ¼nfer', 'Fünfer'
$content = $content -replace 'erhÃ¶ht', 'erhöht'
$content = $content -replace 'fÃ¼ge', 'füge'
$content = $content -replace 'HÃ¤lfte', 'Hälfte'
$content = $content -replace 'Ã¤hnlich', 'ähnlich'

# Pattern title fixes
$content = $content -replace '4×7 o 2×14', '4×7 oder 2×14'
$content = $content -replace 'Relación con la Semana', 'Wochen-Beziehung'
$content = $content -replace 'Patrón del Dígito de las Unidades', 'Einerziffer-Muster'
$content = $content -replace 'Propiedad de Número Primo', 'Primzahl-Eigenschaft'
$content = $content -replace 'Múltiplos Triples de las Decenas', 'Dreifache Zehner-Vielfache'
$content = $content -replace 'Relación con Días del Mes', 'Monatstage-Beziehung'
$content = $content -replace 'Patrón Repdigit', 'Repdigit-Muster'
$content = $content -replace 'Relación Mágica con', 'Magische Beziehung zu'
$content = $content -replace 'Singularidad de Número Primo', 'Primzahl-Einzigartigkeit'
$content = $content -replace 'Propiedades de Número Primo', 'Primzahl-Eigenschaften'
$content = $content -replace '45-4 o 50-9', '45-4 oder 50-9'
$content = $content -replace '2×21 o 3×14', '2×21 oder 3×14'
$content = $content -replace '40\+3 o 45-2', '40+3 oder 45-2'
$content = $content -replace '45\+1 o 50-4', '45+1 oder 50-4'
$content = $content -replace 'Siempre Par y Múltiples Divisores', 'Immer Gerade und Mehrere Teiler'
$content = $content -replace 'Patrón de Número Cuadrado', 'Quadratzahl-Muster'
$content = $content -replace 'Siempre Endet auf', 'Endet auf'
$content = $content -replace 'Patrón de Número de Wochen', 'Wochen-Muster'
$content = $content -replace '50\+3 o 55-2', '50+3 oder 55-2'
$content = $content -replace '2×27 o 3×18', '2×27 oder 3×18'
$content = $content -replace 'Potenz von 3', 'Dreierpotenz'
$content = $content -replace 'Relación (\d+)×(\d+)', '$1×$2 Beziehung'
$content = $content -replace 'Relaciones de Múltiples Factores', 'Mehrfach-Faktor-Beziehungen'
$content = $content -replace 'Siempre Números Pares', 'Immer Gerade Zahlen'
$content = $content -replace 'Siempre Durch', 'Immer durch'
$content = $content -replace '(\d+)-(\d+) Strategie', '$1-$2 Strategie'
$content = $content -replace '(\d+)\+(\d+) Alternative', '$1+$2 Alternative'

# Description patterns
$content = $content -replace 'Relación de número cúbico:', 'Kubikzahl-Beziehung:'
$content = $content -replace '\(múltiplos de (\d+)\)', '(Vielfache von $1)'
$content = $content -replace 'Método de cálculo fácil', 'Einfache Berechnungsmethode'
$content = $content -replace 'Puede calcularse de múltiples formas:', 'Kann auf mehrere Arten berechnet werden:'
$content = $content -replace 'alle múltiplos de (\d+) sind gerade und durch \.\.\. teilbar ([^:]+):', 'Alle Vielfachen von $1 sind gerade und durch $2 teilbar:'
$content = $content -replace 'días = (\d+) Wochen', 'Tage = $1 Wochen'
$content = $content -replace 'Esta relación es útil en cálculos de calendario', 'Diese Beziehung ist nützlich für Kalenderberechnungen'
$content = $content -replace '¡El método más efectivo!', 'Die effektivste Methode!'
$content = $content -replace '¡El método más práctico!', 'Die praktischste Methode!'
$content = $content -replace '¡El más efectivo!', 'Am effektivsten!'
$content = $content -replace '¡Muy práctico!', 'Sehr praktisch!'
$content = $content -replace '¡Muy fácil!', 'Sehr einfach!'
$content = $content -replace 'Dígito de las unidades:', 'Einerziffer:'
$content = $content -replace 'alle múltiplos de (\d+) enden auf (\d+) o (\d+):', 'Alle Vielfachen von $1 enden auf $2 oder $3:'
$content = $content -replace 'alle múltiplos de (\d+) enden auf (\d+):', 'Alle Vielfachen von $1 enden auf $2:'
$content = $content -replace 'alle múltiplos preservan este patrón', 'Alle Vielfachen bewahren dieses Muster'
$content = $content -replace 'tiene patrón especial', 'hat ein spezielles Muster'
$content = $content -replace 'Cadena de duplicación:', 'Verdopplungskette:'
$content = $content -replace 'Die ersten 3 zeigen dígitos dobles', 'Die ersten 3 zeigen Doppelziffern'
$content = $content -replace 'Die ersten 2 zeigen dígitos dobles', 'Die ersten 2 zeigen Doppelziffern'
$content = $content -replace 'dígitos dobles', 'Doppelziffern'
$content = $content -replace 'alle múltiplos de (\d+) son durch \.\.\. teilbar ([^.]+)\.', 'Alle Vielfachen von $1 sind durch $2 teilbar.'
$content = $content -replace 'La suma de dígitos es múltiplo de (\d+)', 'Die Quersumme ist ein Vielfaches von $1'
$content = $content -replace 'Multiplica múltiplos del (\d+) por (\d+)', 'Multipliziere Vielfache von $1 mit $2'
$content = $content -replace 'O múltiplos del (\d+) por (\d+)', 'Oder Vielfache von $1 mit $2'
$content = $content -replace 'Además (\d+)=', 'Außerdem $1='
$content = $content -replace 'Relaciones de múltiples factores', 'Mehrfach-Faktor-Beziehungen'
$content = $content -replace 'Esto lo hace muy útil para fracciones', 'Das macht es sehr nützlich für Brüche'
$content = $content -replace 'Esta relación especial:', 'Diese spezielle Beziehung:'
$content = $content -replace '¡En cada múltiplo de (\d+) hay resultado repdigit!', 'Bei jedem Vielfachen von $1 gibt es ein Repdigit-Ergebnis!'
$content = $content -replace 'Las estrategias (\d+)\+(\d+) o (\d+)-(\d+) son útiles', 'Die Strategien $1+$2 oder $3-$4 sind nützlich'
$content = $content -replace 'Estrategias alternativas:', 'Alternative Strategien:'
$content = $content -replace 'Se puede calcular de múltiples maneras:', 'Kann auf mehrere Arten berechnet werden:'
$content = $content -replace 'Con números grandes:', 'Mit großen Zahlen:'
$content = $content -replace 'Restar de (\d+) es un método alternativo', 'Von $1 subtrahieren ist eine alternative Methode'
$content = $content -replace 'Restar de números redondos', 'Von runden Zahlen subtrahieren'
$content = $content -replace 'Nutze die (\d+)er-Tabelle:', 'Nutze die $1er-Tabelle:'
$content = $content -replace 'O (\d+)×(\d+)×(\d+)', 'Oder $1×$2×$3'
$content = $content -replace 'Múltiplos del (\d+) por (\d+)', 'Vielfache von $1 mit $2'
$content = $content -replace 'También', 'Auch'
$content = $content -replace ' o Verdopple', ' oder verdopple'
$content = $content -replace 'Wochen = 1 año', 'Wochen = 1 Jahr'
$content = $content -replace 'años\)', 'Jahre)'
$content = $content -replace 'Útil en cálculos de calendario', 'Nützlich für Kalenderberechnungen'
$content = $content -replace 'en cálculos de calendario', 'für Kalenderberechnungen'
$content = $content -replace 'es la longitud máxima de un mes', 'ist die maximale Monatslänge'
$content = $content -replace 'erfordert spezielle Strategien', 'erfordert spezielle Strategien'
$content = $content -replace 'Útil si conoces la tabla del (\d+)', 'Nützlich wenn du die $1er-Tabelle kennst'
$content = $content -replace 'Útil cuando multiplicar por (\d+) es más fácil', 'Nützlich wenn Multiplikation mit $1 einfacher ist'
$content = $content -replace 'Útil en cálculos de porcentajes', 'Nützlich für Prozentberechnungen'
$content = $content -replace 'alle múltiplos de (\d+) sind gerade:', 'Alle Vielfachen von $1 sind gerade:'
$content = $content -replace ' o (\d+)', ' oder $1'
$content = $content -replace 'Monate\), 93 \(3 Monate\), 124 \(4 Monate\) en cálculos de calendario', 'Monate), 93 (3 Monate), 124 (4 Monate) für Kalenderberechnungen'

Write-Host "Saving..."
Set-Content -Path $file -Value $content -Encoding UTF8 -NoNewline
Write-Host "All Spanish text translated!"
